#!/bin/bash
# ===============================================
#   M.A.S.O.N. — All-in-One Installer v1.5
#   Mobile Assistant for Screen Observation & Navigation
#   Grok Powered In-Game Vision Assistant
# ===============================================

echo -e "\033[1;36m"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║                   🚀  M.A.S.O.N. v1.5 Installer             ║"
echo "║     Mobile Assistant for Screen Observation & Navigation     ║"
echo "║                    Grok Powered                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "\033[0m"

echo -e "\033[1;33m→ Installing dependencies (Batocera compatible)...\033[0m"
apt update -qq
apt install -y python3 python3-pip python3-tk scrot xclip

echo -e "\033[1;33m→ Creating M.A.S.O.N. directory...\033[0m"
mkdir -p ~/mason/icons
cd ~/mason

echo -e "\033[1;33m→ Installing Python packages...\033[0m"
pip3 install --upgrade pip
pip3 install pillow requests keyboard pyautogui opencv-python-headless

echo -e "\033[1;33m→ Generating M.A.S.O.N. icon...\033[0m"
python3 - << 'PYCODE'
from PIL import Image, ImageDraw, ImageFont
import os
img = Image.new('RGB', (256, 256), color='#0a0a0f')
draw = ImageDraw.Draw(img)
draw.ellipse((32, 32, 224, 224), fill='#1a1a2e', outline='#00ffaa', width=18)
try:
    font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 110)
    draw.text((78, 55), "M", fill="#00ffaa", font=font)
    font2 = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 26)
    draw.text((65, 185), "M.A.S.O.N.", fill="#00cc88", font=font2)
except:
    draw.text((85, 70), "M", fill="#00ffaa")
img.save("icon.png")
img.save("icons/mason_icon.png")
print("✓ Icon created")
PYCODE

# ==================== MAIN M.A.S.O.N. SCRIPT ====================
cat > mason.py << 'EOF'
#!/usr/bin/env python3
import time, os, base64, requests, tkinter as tk
from datetime import datetime
from PIL import ImageGrab
from tkinter import scrolledtext
import keyboard

# ====================== CONFIG ======================
API_KEY = "YOUR_XAI_API_KEY_HERE"          # ← MUST CHANGE THIS
HOTKEY = "ctrl+alt+m"
SAVE_LOG = os.path.expanduser("~/mason/mason_log.txt")
# ===================================================

os.makedirs(os.path.dirname(SAVE_LOG), exist_ok=True)

print(f"[{datetime.now().strftime('%H:%M:%S')}] M.A.S.O.N. v1.5 (Grok Powered) is active | Hotkey: {HOTKEY}")

# Legal Notice
LEGAL_NOTICE = """M.A.S.O.N. is Grok Powered.
This is an unofficial tool created by the community.
Not affiliated with or endorsed by xAI.
All responses are generated by the Grok API.
Use at your own risk. Respect game terms of service."""

def take_screenshot():
    filepath = os.path.expanduser(f"~/mason/mason_shot_{int(time.time())}.png")
    ImageGrab.grab().save(filepath)
    return filepath

def image_to_base64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode('utf-8')

def send_to_grok(image_path):
    base64_img = image_to_base64(image_path)
    prompt = "You are M.A.S.O.N., a real-time in-game AI assistant powered by Grok. Analyze the screenshot: identify the game, current area/situation, and give clear, useful advice — tips, next steps, boss strategies, secrets, or objectives."

    try:
        r = requests.post(
            "https://api.x.ai/v1/chat/completions",
            headers={"Authorization": f"Bearer {API_KEY}"},
            json={
                "model": "grok-2-vision-latest",
                "messages": [{"role": "user", "content": [
                    {"type": "text", "text": prompt},
                    {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{base64_img}"}}
                ]}],
                "max_tokens": 800
            },
            timeout=25
        )
        return r.json()["choices"][0]["message"]["content"] if r.status_code == 200 else f"API Error {r.status_code}"
    except Exception as e:
        return f"Error: {str(e)}"

def show_overlay(text):
    root = tk.Tk()
    root.title("M.A.S.O.N.")
    root.attributes("-alpha", 0.94)
    root.attributes("-topmost", True)
    root.geometry("880x680+1000+80")
    root.configure(bg="#0a0a0f")

    tk.Label(root, text="M.A.S.O.N.", font=("Consolas", 22, "bold"), fg="#00ffaa", bg="#0a0a0f").pack(pady=8)
    tk.Label(root, text="Grok Powered Game Assistant", font=("Consolas", 10), fg="#00cc88", bg="#0a0a0f").pack()

    txt = scrolledtext.ScrolledText(root, bg="#111118", fg="#00ffaa", font=("Consolas", 12), wrap=tk.WORD)
    txt.pack(fill=tk.BOTH, expand=True, padx=20, pady=8)
    txt.insert(tk.END, text + "\n\n" + LEGAL_NOTICE)

    btns = tk.Frame(root, bg="#0a0a0f")
    btns.pack(pady=10)
    tk.Button(btns, text="CLOSE (ESC)", command=root.destroy, bg="#c22", fg="white", font=("Consolas", 11), width=16, height=2).pack(side=tk.LEFT, padx=10)
    tk.Button(btns, text="Save Log", command=lambda: open(SAVE_LOG, "a").write(f"\n--- {datetime.now()} ---\n{text}\n"), bg="#333", fg="white", font=("Consolas", 11)).pack(side=tk.LEFT, padx=10)

    root.bind("<Escape>", lambda e: root.destroy())
    root.mainloop()

def on_hotkey():
    print("→ Screenshot captured → Sending to Grok...")
    img = take_screenshot()
    answer = send_to_grok(img)
    with open(SAVE_LOG, "a") as f:
        f.write(f"[{datetime.now()}] New Analysis\n{answer}\n\n")
    show_overlay(answer)

keyboard.add_hotkey(HOTKEY, on_hotkey)
print("\033[1;32mM.A.S.O.N. (Grok Powered) is now running!\033[0m")
print("Press Ctrl+Alt+M while playing any game.")
keyboard.wait()
EOF

chmod +x mason.py

cat > run-mason.sh << 'EOF'
#!/bin/bash
cd ~/mason
python3 mason.py
EOF
chmod +x run-mason.sh

# Desktop shortcut
cat > ~/.local/share/applications/mason.desktop << EOF
[Desktop Entry]
Name=M.A.S.O.N.
Comment=Grok Powered In-Game Vision Assistant
Exec=$HOME/mason/run-mason.sh
Icon=$HOME/mason/icon.png
Terminal=true
Type=Application
Categories=Game;Utility;
EOF

echo -e "\033[1;32m"
echo "✅ M.A.S.O.N. (Grok Powered) installed successfully!"
echo ""
echo "Next steps:"
echo "1. Get your xAI API key → https://console.x.ai"
echo "2. Edit:   nano ~/mason/mason.py"
echo "3. Run:    ~/mason/run-mason.sh"
echo ""
echo "Hotkey: Ctrl + Alt + M"
echo -e "\033[0m"
